services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Linderp\SuluFormSaveContactBundle\:
        resource: '../../'
        exclude:
          - '../../Resources/'
    Linderp\SuluFormSaveContactBundle\Subscriber\DynamicFormSubscriber:
        tags:
            - { name: 'kernel.event_subscriber'}
    Linderp\SuluFormSaveContactBundle\Service\DynamicFormHandler:
        arguments:
            - !tagged_iterator subscriber.handler
            - '@sulu_contact.contact_manager'
    Linderp\SuluFormSaveContactBundle\Service\FieldHandler\:
        resource: '../../Service/FieldHandler/'
        tags:
            - { name: 'subscriber.handler' }
        exclude:
            - '../../Service/FieldHandler/Exception/'
    Linderp\SuluFormSaveContactBundle\Form\Dynamic\Types\HiddenSaveToContactsFieldType:
        tags:
            - { name: 'sulu_form.dynamic.type', alias: 'hidden_save_to_contacts' }
